CREATE TABLE IF NOT EXISTS `FILE`(
   `filename` VARCHAR(100) NOT NULL,
   `path` VARCHAR(200) NOT NULL,
   `timestamp` INT,
   `size` INT,
   `hash` VARCHAR(32) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `PATH`(
   `dirname` VARCHAR(100) NOT NULL,
   `parentPath` VARCHAR(200) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `LOG`(
   `hash` VARCHAR(32) NOT NULL,
   `status` CHAR(10) NOT NULL,
   `device` VARCHAR(100) NOT NULL,
   `timestamp` INT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

